# Generated by Django 3.1.5 on 2021-01-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('duration', models.DecimalField(decimal_places=1, max_digits=4)),
                ('external_id', models.IntegerField(unique=True)),
                ('last_play', models.DateTimeField()),
                ('artists', models.ManyToManyField(blank=True, to='track.Artist')),
            ],
        ),
    ]
